Hms/Controllers/FloorController.cs
using PMS.Core.Interfaces.HMS;
using PMS.ViewModel.HMS;
using System.Web.Mvc;

namespace Hms.Controllers
{
    public class FloorController : Controller
    {
        private IFloorManager _floorManager;

        public FloorController(IFloorManager floorManager)
        {
            this._floorManager = floorManager;
        }

        public ActionResult Index()
        {
            if (_floorManager.GetCount() > 0)
            {
                ViewBag.Count = _floorManager.GetCount();
                return View(_floorManager.GetAll());
            }
            return View("_EmptyRecord");
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FloorViewModel floor)
        {
            if (ModelState.IsValid)
            {
                if (_floorManager.CheckDuplicate(floor))
                {
                    ViewBag.DuplicateError = "Floor Already Exists!!";
                    return View(floor);
                }
                else
                {
                    _floorManager.Add(floor);
                    return RedirectToAction("Index");
                }
            }
            return View(floor);
        }

        public ActionResult Edit(int id = 0)
        {
            return View(_floorManager.Get(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(FloorViewModel floor)
        {
            if (ModelState.IsValid)
            {
                if (_floorManager.CheckDuplicate(floor))
                {
                    ViewBag.DuplicateError = "Floor Already Exists!!";
                    return View(floor);
                }
                else
                {
                    _floorManager.Edit(floor);
                    return RedirectToAction("Index");
                }
            }
            return View(floor);
        }

        public ActionResult Delete(int id)
        {
            if (ModelState.IsValid)
            {
                _floorManager.Delete(id);
            }
            return RedirectToAction("Index");
        }
    }
}

Hms/Controllers/RoomController.cs
using PMS.Core.Interfaces.HMS;
using System.Web.Mvc;
using PMS.ViewModel.HMS;
using System.Linq;
using System.Threading.Tasks;

namespace Hms.Controllers
{
    public class RoomController : Controller
    {
        private IRoomManager _roomManager;
        private IFloorManager _floorManager;
        private IRoomTypeManager _roomTypeManager;

        public RoomController(IRoomManager roomManager, IFloorManager floorManager, IRoomTypeManager roomTypeManager)
        {
            this._roomManager = roomManager;
            _floorManager = floorManager;
            _roomTypeManager = roomTypeManager;
        }

        public ActionResult Index()
        {
            if (_roomManager.GetCount() > 0)
            {
                ViewBag.Count = _roomManager.GetCount();
                return View(_roomManager.GetAll());
            }
            return View("_EmptyRecord");
        }

        public ActionResult Create()
        {
            var details = new RoomViewModel
            {
                RoomTypeList = _roomTypeManager.GetAll().Where(n => n.Active),
                FloorList = _floorManager.GetAll().Where(n => n.Active)
            };
            return View(details);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RoomViewModel model)
        {
            model.RoomTypeList = _roomTypeManager.GetAll().Where(n => n.Active);
            model.FloorList = _floorManager.GetAll().Where(n => n.Active);

            if (ModelState.IsValid)
            {
                if (_roomManager.CheckDuplicate(model))
                {
                    ViewBag.DuplicateError = "Room Already Exists!!";
                    return View(model);
                }
                else
                {
                    _roomManager.Add(model);
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }

        public ActionResult Edit(int id = 0)
        {
            var model = _roomManager.Get(id);
            model.RoomTypeList = _roomTypeManager.GetAll().Where(n => n.Active);
            model.FloorList = _floorManager.GetAll().Where(n => n.Active);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(RoomViewModel model)
        {
            model.RoomTypeList = _roomTypeManager.GetAll().Where(n => n.Active);
            model.FloorList = _floorManager.GetAll().Where(n => n.Active);
            if (ModelState.IsValid)
            {
                if (_roomManager.CheckDuplicate(model))
                {
                    ViewBag.DuplicateError = "Room Already Exists!!";
                    return View(model);
                }
                else
                {
                    _roomManager.Edit(model);
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }

        public ActionResult Delete(int id)
        {
            if (ModelState.IsValid)
            {
                _roomManager.Delete(id);
            }
            return RedirectToAction("Index");
        }
    }
}

Hms/Views/Shared/_Dashboard_Breadcrumb.cshtml
<div class="content-header row">
    <div class="content-header-left col-md-6 col-xs-12 mb-1">
        <h2 class="content-header-title">@ViewBag.Title</h2>
    </div>
    <div class="content-header-right breadcrumbs-right breadcrumbs-top col-md-6 col-xs-12">
        <div class="breadcrumb-wrapper col-xs-12">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="@Url.Action("Index", "Dashboard")">Home</a></li>
                @{
                    if (ViewBag.ControllerName != null)
                    {
                    <li class="breadcrumb-item"><a href="@Url.Action("Index", ViewBag.ControllerName)">@ViewBag.Title</a></li>
                    }
                    if (ViewBag.MethodName != null)
                    {     
                    <li class="breadcrumb-item active"><a href="#">@ViewBag.MethodName</a></li>
                    }
                }
            </ol>
        </div>
    </div>
</div>

Hms/Views/Shared/_Dashboard_Footer.cshtml
<footer class="footer footer-dark footer-fixed">
    @{
        if (DateTime.Now.Year > 2017)
        {
        <p class="clearfix text-muted text-sm-center mb-0 px-2"><span class="float-md-left d-xs-block d-md-inline-block">Copyright  &copy; 2017 - @DateTime.Now.Year <a href="http://www.infomapsesm.com" target="_blank" class="text-bold-800 grey darken-2">FayBox </a>, All rights reserved. </span><span class="float-md-right d-xs-block d-md-inline-block">Theatre Management System <i class="icon-feed pink"></i></span></p>
        }
        else
        {
        <p class="clearfix text-muted text-sm-center mb-0 px-2"><span class="float-md-left d-xs-block d-md-inline-block">Copyright  &copy; @DateTime.Now.Year <a href="http://www.infomapsesm.com" target="_blank" class="text-bold-800 grey darken-2">FayBox </a>, All rights reserved. </span><span class="float-md-right d-xs-block d-md-inline-block">Theatre Management System <i class="icon-feed pink"></i></span></p>
        }
    }
</footer>

Hms/Views/Shared/_Dashboard_HeaderMenu.cshtml
<!-- navbar-fixed-top-->
<nav class="header-navbar navbar navbar-with-menu navbar-fixed-top navbar-semi-dark navbar-shadow">
    <div class="navbar-wrapper">
        <div class="navbar-header">
            <ul class="nav navbar-nav">
                <li class="nav-item mobile-menu hidden-md-up float-xs-left"><a class="nav-link nav-menu-main menu-toggle hidden-xs"><i class="icon-menu5 font-large-1"></i></a></li>
                <li class="nav-item"><a href="@Url.Action("Index","Dashboard")" class="navbar-brand nav-link">
                    <img alt="branding logo" src="~/Theme/images/logo/robust-logo-light.png" data-expand="../../Theme/images/logo/robust-logo-light.png" data-collapse="../../Theme/images/logo/robust-logo-small.png" class="brand-logo"></a></li>
                <li class="nav-item hidden-md-up float-xs-right"><a data-toggle="collapse" data-target="#navbar-mobile" class="nav-link open-navbar-container"><i class="icon-ellipsis pe-2x icon-icon-rotate-right-right"></i></a></li>
            </ul>
        </div>
        <div class="navbar-container content container-fluid">
            <div id="navbar-mobile" class="collapse navbar-toggleable-sm">
                <ul class="nav navbar-nav">
                    @*<li class="nav-item hidden-sm-down"><a class="nav-link nav-menu-main menu-toggle hidden-xs"><i class="icon-menu5"></i></a></li>*@
                    @*<li class="nav-item hidden-sm-down"><a href="#" class="nav-link nav-link-expand"><i class="ficon icon-expand2"></i></a></li>*@
                </ul>
                <ul class="nav navbar-nav float-xs-right">
                    <li class="nav-item hidden-sm-down"><a href="#" class="nav-link nav-link-expand"><i class="ficon icon-expand2"></i></a></li>
                    <li class="dropdown dropdown-user nav-item">
                        <a href="#" data-toggle="dropdown" class="dropdown-toggle nav-link dropdown-user-link">
                            <span class="avatar avatar-online">
                                <img src="~/Theme/images/avatar.png" alt="avatar"><i></i>
                            </span><span class="user-name">@if (Session["UserName"] != null)
            {@Session["UserName"].ToString()}</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <a href="#" class="dropdown-item"><i class="icon-head"></i>Edit Profile</a>
                            <div class="dropdown-divider"></div>
                            <a href="@Url.Action("Logout","Login")" class="dropdown-item"><i class="icon-power3"></i>Logout</a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>

Hms/Views/Shared/_Dashboard_SideMenu.cshtml
<!-- main menu-->
<div data-scroll-to-active="true" class="main-menu menu-fixed menu-dark menu-accordion menu-shadow">
    <!-- main menu header-->
    <div class="main-menu-header">
        <input type="text" placeholder="Search" class="menu-search form-control round" />
    </div>
    <!-- / main menu header-->
    <!-- main menu content-->
    <div class="main-menu-content">
        <ul id="main-menu-navigation" data-menu="menu-navigation" class="navigation navigation-main">
            <li class="active nav-item"><a href="@Url.Action("Index", "Dashboard")"><i class="icon-home3"></i><span class="menu-title">Dashboard</span></a></li>
            <li class=" nav-item">
                <a href="#"><i class="icon-ticket"></i><span class="menu-title">HMS</span></a>
                <ul class="menu-content">
                    <li>
                        <a href="#" class="menu-item">Configure</a>
                        <ul class="menu-content">
                            <li><a href="@Url.Action("Index","Floor")" class="menu-item">Floor</a></li>
                            <li><a href="@Url.Action("Index","Outlet")" class="menu-item">Outlet</a></li>
                            <li><a href="@Url.Action("Index","Room")" class="menu-item">Room</a></li>
                            <li><a href="@Url.Action("Index","Control")" class="menu-item">Control</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="menu-item">Manage</a>
                        <ul class="menu-content">
                            <li><a href="#" class="menu-item">Check-In Modification</a></li>
                            <li><a href="#" class="menu-item">Advance</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="menu-item">Report</a>
                        <ul class="menu-content">
                            <li><a href="#" class="menu-item">Daily Collection</a></li>
                            <li><a href="#" class="menu-item">Advance Summary</a></li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li class=" nav-item">
                <a href="#"><i class="icon-spoon-knife"></i><span class="menu-title">POS</span></a>
                <ul class="menu-content">
                    <li>
                        <a href="#" class="menu-item">Configure</a>
                        <ul class="menu-content">
                            <li><a href="#" class="menu-item">Floor</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="menu-item">Manage</a>
                        <ul class="menu-content">
                            <li><a href="#" class="menu-item">Check-In Modification</a></li>
                            <li><a href="#" class="menu-item">Advance</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="menu-item">Report</a>
                        <ul class="menu-content">
                            <li><a href="#" class="menu-item">Daily Collection</a></li>
                            <li><a href="#" class="menu-item">Advance Summary</a></li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li class=" nav-item">
                <a href="#"><i class="icon-cogs"></i><span class="menu-title">Settings</span></a>
                <ul class="menu-content">
                    <li><a href="#" class="menu-item">User Management</a></li>
                </ul>
            </li>



            <li class=" navigation-header"><span>Support</span><i data-toggle="tooltip" data-placement="right" data-original-title="Support" class="icon-ellipsis icon-ellipsis"></i></li>
            <li class=" nav-item"><a href="#"><i class="icon-document-text"></i><span data-i18n="nav.support_documentation.main" class="menu-title">Documentation</span></a></li>
        </ul>
    </div>
    <!-- /main menu content-->
    <!-- main menu footer-->
    <!-- include includes/menu-footer-->
    <!-- main menu footer-->
</div>
<!-- / main menu-->

Hms/Views/Shared/_EmptyRecord.cshtml
@{
    Layout = "~/Views/Layout/_DashboardLayout.cshtml";
}

<div class="alert alert-danger"><strong>Sorry!</strong> No records found. <a href="@Url.Action("Create",ViewBag.ControllerName)" class="btn btn-sm btn-orange" accesskey="a"><i class="fa fa-plus"></i>&nbsp;<u>A</u>dd</a>&nbsp;</div>

Hms/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>